-- 媒体信息表（content 域）：一部片/一个条目一行，元数据单独存。
-- 来源优先级：TMDB(采集) → 豆瓣(补录) → 仅录入标题(none)。
CREATE TABLE IF NOT EXISTS `media` (
  `id`              BIGINT       NOT NULL AUTO_INCREMENT,
  `tmdb_id`         INT          DEFAULT NULL            COMMENT 'TMDB id',
  `douban_id`       VARCHAR(20)  DEFAULT NULL            COMMENT '豆瓣 subject id',
  `bangumi_id`      INT          DEFAULT NULL            COMMENT 'Bangumi id',
  `type`            VARCHAR(16)  NOT NULL DEFAULT 'movie' COMMENT 'movie/tv/anime/variety',
  `title`           VARCHAR(255) NOT NULL                COMMENT '标题（中文优先）',
  `original_title`  VARCHAR(255) DEFAULT NULL            COMMENT '原始标题',
  `year`            SMALLINT     DEFAULT NULL            COMMENT '年份',
  `poster`          VARCHAR(512) DEFAULT NULL            COMMENT '海报 URL',
  `backdrop`        VARCHAR(512) DEFAULT NULL            COMMENT '背景图 URL',
  `rating`          DECIMAL(3,1) DEFAULT NULL            COMMENT '评分',
  `overview`        TEXT                                 COMMENT '简介',
  `genres`          VARCHAR(255) DEFAULT NULL            COMMENT '题材标签（逗号分隔）',
  `country`         VARCHAR(128) DEFAULT NULL            COMMENT '国家/地区（逗号分隔）',
  `actors`          VARCHAR(512) DEFAULT NULL            COMMENT '主演（逗号分隔）',
  `directors`       VARCHAR(255) DEFAULT NULL            COMMENT '导演（逗号分隔）',
  `release_date`    VARCHAR(20)  DEFAULT NULL            COMMENT '上映/首播日期',
  `episode_count`   INT          DEFAULT NULL            COMMENT '集数（剧集）',
  `hot`             INT          NOT NULL DEFAULT 0      COMMENT '热度（榜单/排序）',
  `tier`            TINYINT      NOT NULL DEFAULT 0      COMMENT '0普通 1精品 2专区（付费分层预留）',
  `meta_source`     VARCHAR(16)  NOT NULL DEFAULT 'manual' COMMENT 'tmdb/douban/manual/none',
  `pub_status`      TINYINT      NOT NULL DEFAULT 0      COMMENT '0草稿 1已发布 2下架',
  `created_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`         TINYINT      NOT NULL DEFAULT 0      COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tmdb` (`tmdb_id`, `type`),
  UNIQUE KEY `uk_douban` (`douban_id`),
  KEY `idx_type_status` (`type`, `pub_status`),
  KEY `idx_hot` (`hot`),
  KEY `idx_title` (`title`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='媒体信息';
